// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmwobwgxernxygearsqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtd29id2d4ZXJueHlnZWFyc3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDI3ODYsImV4cCI6MjA2MTc3ODc4Nn0.9Dt5HPxeVv_amEmnmWKxQfMEAQPXuYnFOlDlhEqr2C0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);